### ISSUE TITLE
[PROPOSAL] Print functionality

### ISSUE THREAD

**Issue by SelenaZelia** [frank184/FreeEditor#1]
First, nice project !
I may find some times to develop the "print" functionality for the document. Do you accept usage of external library or you want to keep all 'made by hand' ? 
Anyway, if you're still up to that, I'll create a new branch and work on that !

**Comment by frank184** [comment]
Ahaha! I'm glad you like the project! 

If you can get it going I will definitely pull and appreciate it!

**Comment by SelenaZelia** [comment]
Alright I might get it to work without needs of an external API, I'll keep ya tuned
